import type { OfficialTemplateSeed } from './clipmart.types.js'

export const OFFICIAL_TEMPLATES: readonly OfficialTemplateSeed[] = [
  {
    name: 'Standard Cross-Border',
    description: 'Full-stack cross-border e-commerce template with 9 ElectroOS agents, governance rules, and DataOS integration. Suitable for sellers operating on Shopify + Amazon.',
    category: 'full-stack',
    targetMarkets: ['US', 'SG', 'DE', 'JP'],
    targetCategories: ['electronics', 'home', 'beauty'],
    platforms: ['shopify', 'amazon'],
    isOfficial: true,
    config: {
      agents: [
        { type: 'product-scout', name: 'Product Scout', status: 'active', goalContext: { maxProducts: 50, complianceMarkets: ['SG', 'ID', 'DE', 'US'] } },
        { type: 'price-sentinel', name: 'Price Sentinel', status: 'active', goalContext: { approvalThresholdPercent: 15 } },
        { type: 'support-relay', name: 'Support Relay', status: 'active', goalContext: { autoReplyPolicy: 'auto_reply_non_refund' } },
        { type: 'ads-optimizer', name: 'Ads Optimizer', status: 'active', goalContext: { targetRoas: 3.0 } },
        { type: 'inventory-guard', name: 'Inventory Guard', status: 'active', goalContext: { safetyThreshold: 10 } },
        { type: 'content-writer', name: 'Content Writer', status: 'active', goalContext: {} },
        { type: 'market-intel', name: 'Market Intel', status: 'active', goalContext: {} },
        { type: 'finance-agent', name: 'Finance Agent', status: 'active', goalContext: {} },
        { type: 'ceo-agent', name: 'CEO Agent', status: 'active', goalContext: {} },
      ],
      governance: {
        monthlyBudgetUsd: 430,
        priceApprovalThresholdPercent: 15,
        adBudgetApprovalUsd: 500,
        heartbeatIntervalMinutes: 5,
      },
      dataosTier: 'full',
    },
  },
  {
    name: 'SEA Marketplace',
    description: 'Optimized for Southeast Asian multi-platform sellers on TikTok Shop and Shopee. Includes定价, customer support, and advertising agents with regional compliance.',
    category: 'sea',
    targetMarkets: ['SG', 'ID', 'MY', 'TH', 'VN', 'PH'],
    targetCategories: ['fashion', 'beauty', 'home'],
    platforms: ['tiktok', 'shopee'],
    isOfficial: true,
    config: {
      agents: [
        { type: 'product-scout', name: 'Product Scout', status: 'active', goalContext: { maxProducts: 100, complianceMarkets: ['SG', 'ID', 'MY'] } },
        { type: 'price-sentinel', name: 'Price Sentinel', status: 'active', goalContext: { approvalThresholdPercent: 10 } },
        { type: 'support-relay', name: 'Support Relay', status: 'active', goalContext: { autoReplyPolicy: 'auto_reply_non_refund', languages: ['en', 'zh', 'id', 'th'] } },
        { type: 'ads-optimizer', name: 'Ads Optimizer', status: 'active', goalContext: { targetRoas: 2.5 } },
      ],
      governance: {
        monthlyBudgetUsd: 220,
        priceApprovalThresholdPercent: 10,
        adBudgetApprovalUsd: 300,
      },
      dataosTier: 'partial',
    },
  },
  {
    name: 'Amazon PPC Pro',
    description: 'Deep advertising optimization template for Amazon sellers. Ads Optimizer with advanced bid strategies, keyword harvesting, and ACOS targeting.',
    category: 'advertising',
    targetMarkets: ['US', 'DE', 'UK', 'JP'],
    targetCategories: ['electronics', 'supplements', 'outdoor'],
    platforms: ['amazon'],
    isOfficial: true,
    config: {
      agents: [
        { type: 'ads-optimizer', name: 'Ads Optimizer Pro', status: 'active', goalContext: { targetRoas: 4.0, targetAcos: 25, bidStrategy: 'dynamic_down_only', keywordHarvesting: true } },
        { type: 'product-scout', name: 'Product Scout', status: 'active', goalContext: { maxProducts: 200 } },
        { type: 'price-sentinel', name: 'Price Sentinel', status: 'active', goalContext: { approvalThresholdPercent: 10 } },
        { type: 'market-intel', name: 'Market Intel', status: 'active', goalContext: { competitorTracking: true } },
      ],
      governance: {
        monthlyBudgetUsd: 180,
        priceApprovalThresholdPercent: 10,
        adBudgetApprovalUsd: 1000,
      },
      dataosTier: 'partial',
    },
  },
  {
    name: 'Fast Fashion',
    description: 'High-frequency new product launch template for fashion sellers. Emphasizes product scouting, content generation, and inventory management across all platforms.',
    category: 'fashion',
    targetMarkets: ['US', 'UK', 'DE', 'FR'],
    targetCategories: ['fashion', 'accessories', 'shoes'],
    platforms: ['shopify', 'amazon', 'tiktok', 'shopee'],
    isOfficial: true,
    config: {
      agents: [
        { type: 'product-scout', name: 'Product Scout', status: 'active', goalContext: { maxProducts: 500, newProductScanFrequency: 'daily' } },
        { type: 'content-writer', name: 'Content Writer', status: 'active', goalContext: { autoGenerateListings: true, languages: ['en', 'de', 'fr'] } },
        { type: 'inventory-guard', name: 'Inventory Guard', status: 'active', goalContext: { safetyThreshold: 20, fastReplenish: true } },
        { type: 'price-sentinel', name: 'Price Sentinel', status: 'active', goalContext: { approvalThresholdPercent: 20 } },
        { type: 'ads-optimizer', name: 'Ads Optimizer', status: 'active', goalContext: { targetRoas: 2.0 } },
      ],
      governance: {
        monthlyBudgetUsd: 280,
        priceApprovalThresholdPercent: 20,
        adBudgetApprovalUsd: 500,
      },
      dataosTier: 'partial',
    },
  },
  {
    name: 'B2B Wholesale',
    description: 'Enterprise procurement template for B2B wholesale sellers. Includes full agent suite with B2B Harness integration and bulk pricing workflows.',
    category: 'b2b',
    targetMarkets: ['US', 'DE', 'UK'],
    targetCategories: ['industrial', 'office', 'packaging'],
    platforms: ['b2b-portal', 'amazon-business'],
    isOfficial: true,
    config: {
      agents: [
        { type: 'product-scout', name: 'Product Scout', status: 'active', goalContext: { maxProducts: 1000, b2bCatalog: true } },
        { type: 'price-sentinel', name: 'Price Sentinel', status: 'active', goalContext: { approvalThresholdPercent: 5, bulkPricingTiers: true } },
        { type: 'support-relay', name: 'Support Relay', status: 'active', goalContext: { autoReplyPolicy: 'escalate_all', b2bEscalation: true } },
        { type: 'inventory-guard', name: 'Inventory Guard', status: 'active', goalContext: { safetyThreshold: 50, warehouseIntegration: true } },
        { type: 'finance-agent', name: 'Finance Agent', status: 'active', goalContext: { invoicing: true, netTerms: 30 } },
        { type: 'content-writer', name: 'Content Writer', status: 'active', goalContext: { b2bListings: true } },
        { type: 'market-intel', name: 'Market Intel', status: 'active', goalContext: {} },
        { type: 'ads-optimizer', name: 'Ads Optimizer', status: 'active', goalContext: { targetRoas: 5.0 } },
        { type: 'ceo-agent', name: 'CEO Agent', status: 'active', goalContext: {} },
      ],
      governance: {
        monthlyBudgetUsd: 430,
        priceApprovalThresholdPercent: 5,
        adBudgetApprovalUsd: 500,
      },
      dataosTier: 'full',
    },
  },
] as const
