export const PLATFORM_SHOPIFY = 'shopify'
export const DEFAULT_MONTHLY_BUDGET_USD = 50
export const PRICE_APPROVAL_THRESHOLD_PERCENT = 15

/**
 * Loose UUID regex — accepts any 8-4-4-4-12 hex string (case-insensitive)
 * regardless of RFC 4122 version/variant bits.
 *
 * Case-insensitive (`i` flag) to stay backward-compatible with the tenant
 * plugin (`apps/api/src/plugins/tenant.ts`) which has always accepted
 * uppercase UUIDs, and with Zod's built-in `.uuid()` that the routes
 * previously used.  Endpoints that compare header vs body tenant IDs must
 * normalise both sides to lowercase before comparing (see `authGuard` and
 * the `zUuid` transform in `internal-routes.ts`).
 *
 * Zod v4's built-in `.uuid()` enforces strict RFC 4122 (version ∈ [1-8],
 * variant ∈ [89ab]) which rejects perfectly valid UUIDs generated by some
 * databases and test fixtures — hence this looser pattern.
 */
export const UUID_LOOSE_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
