-- Idempotent RLS for ElectroOS when `apply-rls.ts` hits the wrong Postgres on :5432 (local vs Docker).
-- Apply with: docker exec -i patioer-postgres psql -U postgres -d patioer -v ON_ERROR_STOP=1 < scripts/apply-rls-docker-db.sql

ALTER TABLE platform_credentials ENABLE ROW LEVEL SECURITY;
ALTER TABLE platform_credentials FORCE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE products FORCE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE ROW LEVEL SECURITY;
ALTER TABLE agents ENABLE ROW LEVEL SECURITY;
ALTER TABLE agents FORCE ROW LEVEL SECURITY;
ALTER TABLE agent_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE agent_events FORCE ROW LEVEL SECURITY;
ALTER TABLE approvals ENABLE ROW LEVEL SECURITY;
ALTER TABLE approvals FORCE ROW LEVEL SECURITY;
ALTER TABLE webhook_events ENABLE ROW LEVEL SECURITY;
ALTER TABLE webhook_events FORCE ROW LEVEL SECURITY;
ALTER TABLE ads_campaigns ENABLE ROW LEVEL SECURITY;
ALTER TABLE ads_campaigns FORCE ROW LEVEL SECURITY;
ALTER TABLE inventory_levels ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_levels FORCE ROW LEVEL SECURITY;
ALTER TABLE devos_tickets ENABLE ROW LEVEL SECURITY;
ALTER TABLE devos_tickets FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_usage_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_usage_logs FORCE ROW LEVEL SECURITY;
ALTER TABLE billing_reconciliation ENABLE ROW LEVEL SECURITY;
ALTER TABLE billing_reconciliation FORCE ROW LEVEL SECURITY;
ALTER TABLE clipmart_templates ENABLE ROW LEVEL SECURITY;
ALTER TABLE clipmart_templates FORCE ROW LEVEL SECURITY;
ALTER TABLE template_reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE template_reviews FORCE ROW LEVEL SECURITY;
ALTER TABLE referral_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_codes FORCE ROW LEVEL SECURITY;
ALTER TABLE referral_rewards ENABLE ROW LEVEL SECURITY;
ALTER TABLE referral_rewards FORCE ROW LEVEL SECURITY;
ALTER TABLE nps_responses ENABLE ROW LEVEL SECURITY;
ALTER TABLE nps_responses FORCE ROW LEVEL SECURITY;
ALTER TABLE onboarding_progress ENABLE ROW LEVEL SECURITY;
ALTER TABLE onboarding_progress FORCE ROW LEVEL SECURITY;
ALTER TABLE tenant_governance_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE tenant_governance_settings FORCE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_isolation_platform_credentials ON platform_credentials;
CREATE POLICY tenant_isolation_platform_credentials ON platform_credentials USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_products ON products;
CREATE POLICY tenant_isolation_products ON products USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_orders ON orders;
CREATE POLICY tenant_isolation_orders ON orders USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_agents ON agents;
CREATE POLICY tenant_isolation_agents ON agents USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_agent_events ON agent_events;
CREATE POLICY tenant_isolation_agent_events ON agent_events USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_approvals ON approvals;
CREATE POLICY tenant_isolation_approvals ON approvals USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_webhook_events ON webhook_events;
CREATE POLICY tenant_isolation_webhook_events ON webhook_events USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_ads_campaigns ON ads_campaigns;
CREATE POLICY tenant_isolation_ads_campaigns ON ads_campaigns USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_inventory_levels ON inventory_levels;
CREATE POLICY tenant_isolation_inventory_levels ON inventory_levels USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_or_system_devos_tickets ON devos_tickets;
CREATE POLICY tenant_or_system_devos_tickets ON devos_tickets USING (tenant_id IS NULL OR tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_billing_usage_logs ON billing_usage_logs;
CREATE POLICY tenant_isolation_billing_usage_logs ON billing_usage_logs USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_billing_reconciliation ON billing_reconciliation;
CREATE POLICY tenant_isolation_billing_reconciliation ON billing_reconciliation USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS clipmart_template_access ON clipmart_templates;
CREATE POLICY clipmart_template_access ON clipmart_templates USING (is_public = true OR author_tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS template_review_access ON template_reviews;
CREATE POLICY template_review_access ON template_reviews USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_referral_codes ON referral_codes;
CREATE POLICY tenant_isolation_referral_codes ON referral_codes USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_referral_rewards ON referral_rewards;
CREATE POLICY tenant_isolation_referral_rewards ON referral_rewards USING (referrer_tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_nps_responses ON nps_responses;
CREATE POLICY tenant_isolation_nps_responses ON nps_responses USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_onboarding_progress ON onboarding_progress;
CREATE POLICY tenant_isolation_onboarding_progress ON onboarding_progress USING (tenant_id = current_setting('app.tenant_id')::uuid);
DROP POLICY IF EXISTS tenant_isolation_governance_settings ON tenant_governance_settings;
CREATE POLICY tenant_isolation_governance_settings ON tenant_governance_settings USING (tenant_id = current_setting('app.tenant_id')::uuid);
